apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angular-deployment2
spec: 
  selector: 
    matchLabels: 
      app: angular2
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: angular2
    spec:
      terminationGracePeriodSeconds: 30
      containers: 
      - name: angular2
        image: mohitdixit/angular-app:v2
        imagePullPolicy: "Always" 
        ports: 
        - containerPort: 80
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service2
spec: 
  selector: 
    app: angular2
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 31002
  type: NodePort